### ISSUE TITLE
FAT not compatible with current SoFiA version

### ISSUE THREAD

**Issue by ngiese** [PeterKamphuis/FAT#2]
1) The current version of SoFiA only returns certain source parameters when doParameterise=true in the SoFiA input parameter file. The flux related parameters ('f_int', 'f_peak', 'f_wm50' - names might have changed compared to previous versions) belong to this particular group. This is important because FAT needs these parameters (e.g. in line 1076) and terminates if they are not present and the array holding the source parameters is too short for the provided index (17 in the following error message):

```
% Attempt to subscript VALS with <LONG     (          17)> is out of range.
```

2) The indices of source parameters that are used are hard coded in FAT. Even if doParameterise is set to 'true', the wrong source parameter values will be used in some cases, e.g.

```
line 1076: Totflux=[double(vals[17])]
```

The parameter index of the total flux in the catalogue that is returned by SoFiA is 18, the index of 17 corresponds to the position angle that has been determined by ellipse fitting. Thus, the wrong value is used. It might be better to get the parameter index from the name in the catalogue file ('f_int' in this case).

**Comment by PeterKamphuis** [comment]
FAT is now compatible with SoFiA v0.5.0 and the suggestion of using flexible column identification has been implemented. This gives the user the opportunity to add output parameters in Support/sofiainput.txt. However, it seems that many of the parameters displayed in the GUI are not yet available as they provide a not defined warning. To avoid problems with SoFiA changing column names a check that all required columns are present has been build in and, before the code stops, an error message will appear if one is missing.

Due to SoFiA switching between SNR and flux the treatment of flux and HI mass had become somewhat buggy. This  is now reviewed throughout the code and should now be proper.

Additionally there was an issue with NAXIS3
